// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findUserByUserUuid = `-- name: FindUserByUserUuid :one
SELECT users.uuid, name, username, email, password
FROM users
WHERE uuid = $1
AND deleted_at IS NULL
`

type FindUserByUserUuidRow struct {
	Uuid     uuid.UUID      `json:"uuid"`
	Name     sql.NullString `json:"name"`
	Username sql.NullString `json:"username"`
	Email    string         `json:"email"`
	Password sql.NullString `json:"password"`
}

func (q *Queries) FindUserByUserUuid(ctx context.Context, argUuid uuid.UUID) (FindUserByUserUuidRow, error) {
	row := q.db.QueryRow(ctx, findUserByUserUuid, argUuid)
	var i FindUserByUserUuidRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const updatePassowrd = `-- name: UpdatePassowrd :exec
UPDATE users
SET password = $1, last_modified_at = $2
WHERE uuid = $3
AND deleted_at IS NULL
`

type UpdatePassowrdParams struct {
	Password       sql.NullString `json:"password"`
	LastModifiedAt time.Time      `json:"last_modified_at"`
	Uuid           uuid.UUID      `json:"uuid"`
}

func (q *Queries) UpdatePassowrd(ctx context.Context, arg UpdatePassowrdParams) error {
	_, err := q.db.Exec(ctx, updatePassowrd, arg.Password, arg.LastModifiedAt, arg.Uuid)
	return err
}
