// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package roledb

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type GooseDbVersion struct {
	ID        int32     `json:"id"`
	VersionID int64     `json:"version_id"`
	IsApplied bool      `json:"is_applied"`
	Tstamp    time.Time `json:"tstamp"`
}

type Role struct {
	Uuid        uuid.UUID   `json:"uuid"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type User struct {
	Uuid           uuid.UUID      `json:"uuid"`
	CreatedAt      time.Time      `json:"created_at"`
	LastModifiedAt time.Time      `json:"last_modified_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	CreatedBy      sql.NullString `json:"created_by"`
	Email          string         `json:"email"`
	Name           sql.NullString `json:"name"`
	Password       sql.NullString `json:"password"`
	VerifiedAt     sql.NullTime   `json:"verified_at"`
	Username       sql.NullString `json:"username"`
}

type UserRole struct {
	UserUuid uuid.UUID `json:"user_uuid"`
	RoleUuid uuid.UUID `json:"role_uuid"`
}
