openapi: 3.0.0
info:
  title: User Management API
  version: 1.0.0
paths:
  /login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: User login successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Login"
  /password/reset:init:
    post:
      summary: Initiate password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        "200":
          description: Password reset initiated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
  /password/reset:
    post:
      summary: Reset password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PasswordReset"
      responses:
        "200":
          description: Password reset successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /password/reset:init:
    post:
      summary: Initiate password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: Password reset email sent
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /token/refresh:
    get:
      summary: Refresh JWT tokens
      parameters:
        - name: refreshToken
          in: query
          required: true
          schema:
            type: string
            example: "jwt_refresh_token"
      responses:
        '200':
          description: Tokens refreshed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'

components:
  schemas:
    Login:
      type: object
      properties:
        status:
          type: string
          example: success
        message:
          type: string
        refreshToken:
          type: string
        accessToken:
          type: string
        user:
          $ref: "#/components/schemas/User"
      required:
        - status
        - message
        - refreshToken
        - accessToken
        - user
    User:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
        email:
          type: string
      required:
        - uuid
        - name
        - email
    PasswordReset:
      type: object
      properties:
        code:
          type: string
        password:
          type: string
      required:
        - code
        - password
    PasswordResetInit:
      type: object
      properties:
        email:
          type: string
      required:
        - email
    Tokens:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
