// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package logindb

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findLoginByUsername = `-- name: FindLoginByUsername :one
SELECT l.id, l.username, l.password, l.created_at, l.updated_at
FROM login l
WHERE l.username = $1
AND l.deleted_at IS NULL
`

type FindLoginByUsernameRow struct {
	ID        uuid.UUID      `json:"id"`
	Username  sql.NullString `json:"username"`
	Password  []byte         `json:"password"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) FindLoginByUsername(ctx context.Context, username sql.NullString) (FindLoginByUsernameRow, error) {
	row := q.db.QueryRow(ctx, findLoginByUsername, username)
	var i FindLoginByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUser = `-- name: FindUser :one
SELECT id, username, password
FROM login
WHERE username = $1
AND deleted_at IS NULL
`

type FindUserRow struct {
	ID       uuid.UUID      `json:"id"`
	Username sql.NullString `json:"username"`
	Password []byte         `json:"password"`
}

func (q *Queries) FindUser(ctx context.Context, username sql.NullString) (FindUserRow, error) {
	row := q.db.QueryRow(ctx, findUser, username)
	var i FindUserRow
	err := row.Scan(&i.ID, &i.Username, &i.Password)
	return i, err
}

const findUserInfoWithRoles = `-- name: FindUserInfoWithRoles :one
SELECT u.email, u.username, u.name, COALESCE(array_agg(r.name), '{}') AS roles
FROM users u
LEFT JOIN user_roles ur ON u.id = ur.user_id
LEFT JOIN roles r ON ur.role_id = r.id
WHERE u.id = $1
AND u.deleted_at IS NULL
GROUP BY u.email, u.username, u.name
`

type FindUserInfoWithRolesRow struct {
	Email    string         `json:"email"`
	Username sql.NullString `json:"username"`
	Name     sql.NullString `json:"name"`
	Roles    interface{}    `json:"roles"`
}

func (q *Queries) FindUserInfoWithRoles(ctx context.Context, id uuid.UUID) (FindUserInfoWithRolesRow, error) {
	row := q.db.QueryRow(ctx, findUserInfoWithRoles, id)
	var i FindUserInfoWithRolesRow
	err := row.Scan(
		&i.Email,
		&i.Username,
		&i.Name,
		&i.Roles,
	)
	return i, err
}

const findUserRolesByUserId = `-- name: FindUserRolesByUserId :many
SELECT r.name
FROM user_roles ur
LEFT JOIN roles r ON ur.role_id = r.id
WHERE ur.user_id = $1
`

func (q *Queries) FindUserRolesByUserId(ctx context.Context, userID uuid.UUID) ([]sql.NullString, error) {
	rows, err := q.db.Query(ctx, findUserRolesByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var name sql.NullString
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUsernameByEmail = `-- name: FindUsernameByEmail :one
SELECT u.username
FROM users u
WHERE u.email = $1
AND u.deleted_at IS NULL
`

func (q *Queries) FindUsernameByEmail(ctx context.Context, email string) (sql.NullString, error) {
	row := q.db.QueryRow(ctx, findUsernameByEmail, email)
	var username sql.NullString
	err := row.Scan(&username)
	return username, err
}

const get2FAByLoginId = `-- name: Get2FAByLoginId :one
SELECT u.two_factor_secret
FROM users u
JOIN login l ON l.user_id = u.id
WHERE l.id = $1
AND u.deleted_at IS NULL
`

func (q *Queries) Get2FAByLoginId(ctx context.Context, id uuid.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, get2FAByLoginId, id)
	var two_factor_secret pgtype.Text
	err := row.Scan(&two_factor_secret)
	return two_factor_secret, err
}

const get2FASecret = `-- name: Get2FASecret :one
SELECT two_factor_secret
FROM users
WHERE users.id = $1
AND deleted_at IS NULL
`

func (q *Queries) Get2FASecret(ctx context.Context, id uuid.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, get2FASecret, id)
	var two_factor_secret pgtype.Text
	err := row.Scan(&two_factor_secret)
	return two_factor_secret, err
}

const getLoginById = `-- name: GetLoginById :one
SELECT l.id as login_id, l.username, l.password, l.created_at, l.updated_at,
       l.two_factor_enabled, l.two_factor_secret, l.two_factor_backup_codes
FROM login l
WHERE l.id = $1
AND l.deleted_at IS NULL
`

type GetLoginByIdRow struct {
	LoginID              uuid.UUID      `json:"login_id"`
	Username             sql.NullString `json:"username"`
	Password             []byte         `json:"password"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	TwoFactorEnabled     pgtype.Bool    `json:"two_factor_enabled"`
	TwoFactorSecret      pgtype.Text    `json:"two_factor_secret"`
	TwoFactorBackupCodes []string       `json:"two_factor_backup_codes"`
}

func (q *Queries) GetLoginById(ctx context.Context, id uuid.UUID) (GetLoginByIdRow, error) {
	row := q.db.QueryRow(ctx, getLoginById, id)
	var i GetLoginByIdRow
	err := row.Scan(
		&i.LoginID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TwoFactorEnabled,
		&i.TwoFactorSecret,
		&i.TwoFactorBackupCodes,
	)
	return i, err
}

const getUsersByLoginId = `-- name: GetUsersByLoginId :many
SELECT u.id, u.username, u.name, u.email, u.created_at, u.last_modified_at,
       COALESCE(array_agg(r.name) FILTER (WHERE r.name IS NOT NULL), '{}') as roles
FROM users u
LEFT JOIN user_roles ur ON u.id = ur.user_id
LEFT JOIN roles r ON ur.role_id = r.id
WHERE u.login_id = $1
AND u.deleted_at IS NULL
GROUP BY u.id, u.username, u.name, u.email, u.created_at, u.last_modified_at
`

type GetUsersByLoginIdRow struct {
	ID             uuid.UUID      `json:"id"`
	Username       sql.NullString `json:"username"`
	Name           sql.NullString `json:"name"`
	Email          string         `json:"email"`
	CreatedAt      time.Time      `json:"created_at"`
	LastModifiedAt time.Time      `json:"last_modified_at"`
	Roles          interface{}    `json:"roles"`
}

func (q *Queries) GetUsersByLoginId(ctx context.Context, loginID uuid.NullUUID) ([]GetUsersByLoginIdRow, error) {
	rows, err := q.db.Query(ctx, getUsersByLoginId, loginID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByLoginIdRow
	for rows.Next() {
		var i GetUsersByLoginIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.LastModifiedAt,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const initPasswordByUsername = `-- name: InitPasswordByUsername :one
SELECT id
FROM login
WHERE username = $1
`

func (q *Queries) InitPasswordByUsername(ctx context.Context, username sql.NullString) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, initPasswordByUsername, username)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const initPasswordResetToken = `-- name: InitPasswordResetToken :exec
INSERT INTO login_password_reset_tokens (login_id, token, expire_at)
VALUES ($1, $2, $3)
`

type InitPasswordResetTokenParams struct {
	LoginID  uuid.UUID          `json:"login_id"`
	Token    string             `json:"token"`
	ExpireAt pgtype.Timestamptz `json:"expire_at"`
}

func (q *Queries) InitPasswordResetToken(ctx context.Context, arg InitPasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, initPasswordResetToken, arg.LoginID, arg.Token, arg.ExpireAt)
	return err
}

const markBackupCodeUsed = `-- name: MarkBackupCodeUsed :exec
UPDATE login l
SET two_factor_backup_codes = array_remove(two_factor_backup_codes, $1::text)
WHERE l.id = $2
AND l.deleted_at IS NULL
`

type MarkBackupCodeUsedParams struct {
	Code string    `json:"code"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) MarkBackupCodeUsed(ctx context.Context, arg MarkBackupCodeUsedParams) error {
	_, err := q.db.Exec(ctx, markBackupCodeUsed, arg.Code, arg.ID)
	return err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE login_password_reset_tokens
SET used_at = NOW()
WHERE token = $1
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, markPasswordResetTokenUsed, token)
	return err
}

const registerUser = `-- name: RegisterUser :one
WITH new_login AS (
  INSERT INTO login (username, password)
  VALUES ($1, $4)
  RETURNING id
)
INSERT INTO users (login_id, username, email, name)
SELECT nl.id, $1, $2, $3
FROM new_login nl
RETURNING id, username, email, name, created_at, last_modified_at, deleted_at
`

type RegisterUserParams struct {
	Username sql.NullString `json:"username"`
	Email    string         `json:"email"`
	Name     sql.NullString `json:"name"`
	Password []byte         `json:"password"`
}

type RegisterUserRow struct {
	ID             uuid.UUID      `json:"id"`
	Username       sql.NullString `json:"username"`
	Email          string         `json:"email"`
	Name           sql.NullString `json:"name"`
	CreatedAt      time.Time      `json:"created_at"`
	LastModifiedAt time.Time      `json:"last_modified_at"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (RegisterUserRow, error) {
	row := q.db.QueryRow(ctx, registerUser,
		arg.Username,
		arg.Email,
		arg.Name,
		arg.Password,
	)
	var i RegisterUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
		&i.LastModifiedAt,
		&i.DeletedAt,
	)
	return i, err
}

const resetPassword = `-- name: ResetPassword :exec
UPDATE login
SET password = $1, 
    last_modified_at = NOW()
WHERE username = $2
`

type ResetPasswordParams struct {
	Password []byte         `json:"password"`
	Username sql.NullString `json:"username"`
}

func (q *Queries) ResetPassword(ctx context.Context, arg ResetPasswordParams) error {
	_, err := q.db.Exec(ctx, resetPassword, arg.Password, arg.Username)
	return err
}

const resetPasswordById = `-- name: ResetPasswordById :exec
UPDATE login
SET password = $1,
    updated_at = NOW()
WHERE login.id = $2
`

type ResetPasswordByIdParams struct {
	Password []byte    `json:"password"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) ResetPasswordById(ctx context.Context, arg ResetPasswordByIdParams) error {
	_, err := q.db.Exec(ctx, resetPasswordById, arg.Password, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE login
SET password = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	Password []byte    `json:"password"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.Password, arg.ID)
	return err
}

const validateBackupCode = `-- name: ValidateBackupCode :one
SELECT EXISTS (
  SELECT 1
  FROM login l
  WHERE l.id = $1
  AND $2::text = ANY(l.two_factor_backup_codes)
  AND l.deleted_at IS NULL
) AS is_valid
`

type ValidateBackupCodeParams struct {
	ID   uuid.UUID `json:"id"`
	Code string    `json:"code"`
}

func (q *Queries) ValidateBackupCode(ctx context.Context, arg ValidateBackupCodeParams) (bool, error) {
	row := q.db.QueryRow(ctx, validateBackupCode, arg.ID, arg.Code)
	var is_valid bool
	err := row.Scan(&is_valid)
	return is_valid, err
}

const validatePasswordResetToken = `-- name: ValidatePasswordResetToken :one
SELECT prt.id as id, prt.login_id as login_id
FROM login_password_reset_tokens prt
JOIN login l ON l.id = prt.login_id 
WHERE prt.token = $1
  AND prt.expire_at > NOW()
  AND prt.used_at IS NULL
LIMIT 1
`

type ValidatePasswordResetTokenRow struct {
	ID      uuid.UUID `json:"id"`
	LoginID uuid.UUID `json:"login_id"`
}

func (q *Queries) ValidatePasswordResetToken(ctx context.Context, token string) (ValidatePasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, validatePasswordResetToken, token)
	var i ValidatePasswordResetTokenRow
	err := row.Scan(&i.ID, &i.LoginID)
	return i, err
}
