openapi: 3.0.0
info:
  title: Logins Management API
  version: 1.0.0
paths:
  /:
    get:
      summary: List all logins
      parameters:
        - name: limit
          in: query
          description: Maximum number of logins to return
          required: false
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          description: Offset for pagination
          required: false
          schema:
            type: integer
            default: 0
        - name: search
          in: query
          description: Search term for filtering logins
          required: false
          schema:
            type: string
      responses:
        "200":
          description: List of logins
          content:
            application/json:
              schema:
                type: object
                properties:
                  logins:
                    type: array
                    items:
                      $ref: "#/components/schemas/Login"
                  total:
                    type: integer
                    description: Total number of logins
    post:
      summary: Create a new login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateLoginRequest"
      responses:
        "201":
          description: Login created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Login"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Username already exists"
  
  /{id}:
    get:
      summary: Get login by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Login details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Login"
        "404":
          description: Login not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Login not found"
    put:
      summary: Update login
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateLoginRequest"
      responses:
        "200":
          description: Login updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Login"
        "404":
          description: Login not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Login not found"
    delete:
      summary: Delete login
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Login deleted successfully
        "404":
          description: Login not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Login not found"
  
  /{id}/2fa:
    get:
      operationId: get_2fa_methods_by_login_id
      summary: Get login 2FA methods
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: 2FA method found successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TwoFactorMethods"
        "404":
          description: Login 2fa methods not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Login 2fa methods not found"
  /{id}/2fa/setup:
    post:
      summary: Create a new 2FA method
      operationId: post_2fa_setup
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                twofa_type:
                  type: string
                  enum: ["email", "sms", "authenticator_app"]
              required:
                - twofa_type
      responses:
        "201":
          description: 2FA method created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        "400":
          description: Invalid request parameters
        "409":
          description: 2FA method already exists
        "500":
          description: Internal server error
  /{id}/2fa/enable:
    post:
      summary: Enable an existing 2FA method
      operationId: post_2fa_enable
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                twofa_type:
                  type: string
                  enum: ["email", "sms", "authenticator_app"]
              required:
                - twofa_type
      responses:
        "200":
          description: 2FA method enabled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        "400":
          description: Invalid request parameters
        "404":
          description: 2FA method not found
        "500":
          description: Internal server error
  /{id}/2fa/disable:
    post:
      summary: Disable an existing 2FA method
      operationId: post_2fa_disable
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                twofa_type:
                  type: string
                  enum: ["email", "sms", "authenticator_app"]
              required:
                - twofa_type
      responses:
        "200":
          description: 2FA method disabled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        "400":
          description: Invalid request parameters
        "404":
          description: 2FA method not found
        "500":
          description: Internal server error

components:
  schemas:
    Login:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        two_factor_enabled:
          type: boolean
        password_version:
          type: integer
    
    CreateLoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    
    UpdateLoginRequest:
      type: object
      x-go-optional-value: true
      properties:
        username:
          type: string
      required:
        - username
  
    TwoFactorMethods:
      type: object
      properties:
        methods:
          type: array
          items:
            $ref: "#/components/schemas/TwoFactorMethod"
        count:
          type: integer
      required:
        - methods
        - count
    
    TwoFactorMethod:
      x-go-optional-value: true
      type: object
      properties:
        two_factor_id:
          type: string
          format: uuid
        type:
          type: string
        enabled:
          type: boolean
      required:
        - type
        - enabled
    SuccessResponse:
      x-go-optional-value: true
      type: object
      properties:
        result:
          type: string
